name: Java CI

# Run CI on these branches
on:
  push:
    branches: [ main, dev, 'feature/**', 'sprint**' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    # Use Ubuntu as the virtual machine
    runs-on: ubuntu-latest

    steps:
      # Pull the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #speed up build time
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Clean, build, and test
      - name: Build with Maven
        run: mvn -B clean verify
